### ISSUE TITLE
fontquery-diff should exit non-zero if there are any differences

### ISSUE THREAD

**Issue by AdamWill** [fedora-i18n/fontquery#5]
[adamw@xps13a fontquery (main)]$ fontquery-diff -l he 40
    * Comparison between 40 and local
    * This may take some time...
      Language                                        default sans                                    default serif                                   default mono                                   
    - Hebrew(he)                                      Noto Sans Hebrew                                Noto Serif Hebrew                               Noto Sans Hebrew                               
    +                                                                                                                                                 Liberation Mono                                
    [adamw@xps13a fontquery (main)]$ echo $?
    0

this is a problem for automation. We need to know whether the script "passed" (there were no differences) or "failed" (there were differences), and the exit code is the normal way to do that. Comparing the output and looking whether it contains plus or minus signs is much messier and more fragile.

**Comment by tagoh** [comment]
Thank you for your suggestion. I also added `--loose-comparison` option to stop reporting the case of 'same family name but different file' as difference. FYI.

**Comment by AdamWill** [comment]
the fix wasn't complete, https://github.com/fedora-i18n/fontquery/pull/8 is also needed.
