### ISSUE TITLE
rawhide: fontquery -r local: requires use of container?

### ISSUE THREAD

**Issue by juhp** [fedora-i18n/fontquery#7]
I haven't looked into the code but it seems `fontquery -r local` triggers `fontquery-container`
which in turns runs podman. Or is something wrong in my system?
This only seems to happen with fontquery-1.10, not 1.8 from my testing.

```
⬢ fedora41~$ fontquery -r local
python: can't open file '/var/home/petersen/fontquery-container': [Errno 2] No such file or directory
RuntimeError: `podman run' failed with the error code 2
```

Shouldn't `-r local` still work even without podman?

**Comment by tagoh** [comment]
No, it is a bug in fontquery and running podman is a side effect.
